import { FilesetResolver, PoseLandmarker } from '@mediapipe/tasks-vision';
import { LandmarkPoint, LandmarkOneEuroFilter } from './poseGeometry';
export type TrackerStatus='idle'|'loading'|'ready'|'error';
export interface PoseDetection {image:LandmarkPoint[];world:LandmarkPoint[];timestamp:number;trackId:number;trackScore:number;}
interface Track {id:number;center:{x:number;y:number};size:number;score:number;lastSeen:number;}
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
const centerOf=(p:LandmarkPoint[])=>{const ids=[0,11,12,23,24,25,26,27,28];const q=ids.map(i=>p[i]).filter(Boolean);return {x:q.reduce((s,v)=>s+v.x,0)/q.length,y:q.reduce((s,v)=>s+v.y,0)/q.length};};
const sizeOf=(p:LandmarkPoint[])=>{const xs=p.map(v=>v.x),ys=p.map(v=>v.y);return Math.max(.05,(Math.max(...xs)-Math.min(...xs))*(Math.max(...ys)-Math.min(...ys)));};
export class MediaPipeTracker{
 private landmarker:PoseLandmarker|null=null; public status:TrackerStatus='idle'; private filter=new LandmarkOneEuroFilter(); private initPromise:Promise<boolean>|null=null;
 public lastFps=0; private frames=0; private fpsAt=performance.now(); private lastTimestamp=-1; private track:Track|null=null; private nextId=1; private missed=0;
 public async initialize():Promise<boolean>{if(this.landmarker&&this.status==='ready')return true;if(this.initPromise)return this.initPromise;this.status='loading';this.initPromise=(async()=>{try{const vision=await FilesetResolver.forVisionTasks('/mediapipe/wasm').catch(()=>FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm'));const create=(delegate:'GPU'|'CPU',modelAssetPath:string)=>PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath,delegate},runningMode:'VIDEO',numPoses:4,minPoseDetectionConfidence:.5,minPosePresenceConfidence:.5,minTrackingConfidence:.5});try{this.landmarker=await create('GPU','/mediapipe/pose_landmarker_lite.task').catch(()=>create('CPU','/mediapipe/pose_landmarker_lite.task'));}catch{const remote='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task';this.landmarker=await create('GPU',remote).catch(()=>create('CPU',remote));}this.status='ready';return true;}catch(e){console.warn('[MediaPipe] init failed',e);this.status='error';return false;}finally{this.initPromise=null;}})();return this.initPromise;}
 private choose(poses:LandmarkPoint[][]):{pose:LandmarkPoint[];id:number;score:number}|null{
  if(!poses.length)return null; const candidates=poses.map((p,i)=>{const c=centerOf(p),s=sizeOf(p),v=p.reduce((a,x)=>a+(x.visibility??1),0)/Math.max(1,p.length);let score=v*.35+clamp(s/.12)*.2;if(this.track){const d=Math.hypot(c.x-this.track.center.x,c.y-this.track.center.y);const scale=1-Math.min(1,d/.45);const size=1-Math.min(1,Math.abs(Math.log(s/this.track.size))/1.5);score+=scale*.3+size*.15;}return {pose:p,id:i,score,center:c,size:s};});
  candidates.sort((a,b)=>b.score-a.score);const best=candidates[0];if(this.track){const d=Math.hypot(best.center.x-this.track.center.x,best.center.y-this.track.center.y);if(d>.45&&this.missed<6)return null;}
  if(!this.track)this.track={id:this.nextId++,center:best.center,size:best.size,score:best.score,lastSeen:performance.now()};else this.track={...this.track,center:best.center,size:best.size,score:best.score,lastSeen:performance.now()};this.missed=0;return {pose:best.pose,id:this.track.id,score:best.score};
 }
 public detect(video:HTMLVideoElement,timestamp:number):PoseDetection|null{if(!this.landmarker||this.status!=='ready'||timestamp<=this.lastTimestamp)return null;this.lastTimestamp=timestamp;try{const r=this.landmarker.detectForVideo(video,timestamp);const raw=r.landmarks?.map(x=>x.map((lm:any)=>({x:lm.x,y:lm.y,z:lm.z??0,visibility:lm.visibility??1})))??[];const chosen=this.choose(raw);if(!chosen){this.missed++;return null;}const image=this.filter.smooth(chosen.pose,timestamp);const worldRaw=r.worldLandmarks?.[chosen.id]??chosen.pose;const world=worldRaw.map((lm:any)=>({x:lm.x,y:lm.y,z:lm.z??0,visibility:lm.visibility??1}));this.frames++;const now=performance.now();if(now-this.fpsAt>=1000){this.lastFps=this.frames;this.frames=0;this.fpsAt=now;}return {image,world,timestamp,trackId:chosen.id,trackScore:chosen.score};}catch{return null;}}
 public resetFilter(){this.filter.reset();this.lastTimestamp=-1;this.track=null;this.missed=0;}
 public close(){try{this.landmarker?.close();}catch{}this.landmarker=null;this.status='idle';this.initPromise=null;this.resetFilter();}
}
export const mediaPipeTracker=new MediaPipeTracker();
