import { ExerciseId } from '../types';
import { EXERCISE_RULES, Strictness } from './exerciseRules';
import { LandmarkPoint, LANDMARKS, calculateJointAngle3D } from './poseGeometry';
import { ViewEstimate } from './viewEstimator';
export type RepError='incomplete_rom'|'pelvis_sag'|'rushing_tempo'|'low_confidence'|'bad_view'|'poor_form';
export interface RepResult{counted:boolean;count:number;rom:number;confidence:number;phase:'up'|'down'|'hold'|'paused';error?:RepError;signal:string;}
const v=(p?:LandmarkPoint)=>p?.visibility??0; const clamp=(x:number,a=0,b=1)=>Math.max(a,Math.min(b,x));
export class RepCounter{
 private phase:'up'|'down'|'hold'|'paused'='up'; private count=0; private peak=0; private lastRepTs=0; private lowSince=0; private calibrated=false; private startTs=0;
 constructor(private exerciseId:ExerciseId,private strictness:Strictness='standard'){}
 reset(){this.phase='up';this.count=0;this.peak=0;this.lastRepTs=0;this.lowSince=0;this.calibrated=false;this.startTs=0;}
 get totalReps(){return this.count;}
 private requiredConfidence(p:LandmarkPoint[],ids:number[],view:ViewEstimate){const vals=ids.map(i=>v(p[i]));const min=vals.length?Math.min(...vals):0;const avg=vals.reduce((a,b)=>a+b,0)/Math.max(1,vals.length);const temporal=view.quality;return clamp(min*.65+avg*.2+temporal*.15);}
 private angle(p:LandmarkPoint[],a:number,b:number,c:number){const A=p[a],B=p[b],C=p[c];return A&&B&&C?calculateJointAngle3D(A,B,C):180;}
 private signal(p:LandmarkPoint[]):number{const rule=EXERCISE_RULES[this.exerciseId];switch(rule.signal){case'elbow':{const l=this.angle(p,11,13,15),r=this.angle(p,12,14,16);return (l+r)/2;}case'knee':case'lunge':{const l=this.angle(p,23,25,27),r=this.angle(p,24,26,28);return (l+r)/2;}case'dip':{const l=this.angle(p,11,13,15),r=this.angle(p,12,14,16);return (l+r)/2;}case'jack':{const sw=Math.max(.001,Math.hypot(p[11]?.x-p[12]?.x||0,p[11]?.y-p[12]?.y||0));const hand=Math.max(p[15]?.y??1,p[16]?.y??1)-Math.min(p[11]?.y??1,p[12]?.y??1);const feet=Math.hypot((p[27]?.x??0)-(p[28]?.x??0),(p[27]?.y??0)-(p[28]?.y??0))/sw;return clamp((-hand*300+feet*50)/100)*100;}case'burpee':return this.angle(p,11,23,27);case'plank':return this.angle(p,11,23,27);}}
 private normalize(angle:number){return clamp((170-angle)/(170-75))*100;}
 private currentRom(p:LandmarkPoint[]){return this.normalize(this.signal(p));}
 private formCheck(p:LandmarkPoint[]):RepError|undefined{if(this.exerciseId==='pushups'){const a=p[11],h=p[23],an=p[27];if(a&&h&&an&&Math.abs(180-calculateJointAngle3D(a,h,an))>28)return'pelvis_sag';}if(this.exerciseId==='plank'){const a=p[11],h=p[23],an=p[27];if(a&&h&&an&&Math.abs(180-calculateJointAngle3D(a,h,an))>20)return'poor_form';}return undefined;}
 process(p:LandmarkPoint[],view:ViewEstimate,now=performance.now()):RepResult{const rule=EXERCISE_RULES[this.exerciseId];const conf=this.requiredConfidence(p,rule.required,view);if(view.view==='unknown'||view.quality<.35||conf<.5||rule.invalidViews?.includes(view.view as any)){if(!this.lowSince)this.lowSince=now;this.phase='paused';return{counted:false,count:this.count,rom:this.currentRom(p),confidence:conf,phase:'paused',signal:rule.signal,error:now-this.lowSince>400?'low_confidence':'bad_view'};}this.lowSince=0;if(this.exerciseId==='plank')return this.plank(p,now,conf);const form=this.formCheck(p);if(form)return{counted:false,count:this.count,rom:this.currentRom(p),confidence:conf,phase:this.phase==='hold'?'hold':this.phase,signal:rule.signal,error:form};const rom=this.currentRom(p);if(!this.calibrated){if(this.phase==='up'&&rom<20)this.calibrated=true;else return{counted:false,count:this.count,rom,confidence:conf,phase:'up',signal:rule.signal};}
  const targetRom=Math.max(15,rule.minRom[this.strictness]); const startThreshold=Math.max(8,targetRom*.20);
  if(this.phase==='up'&&rom>=targetRom){this.phase='down';this.startTs=now;this.peak=rom;}
  else if(this.phase==='down'){this.peak=Math.max(this.peak,rom);if(rom<=startThreshold){const duration=now-this.startTs;const validRom=this.peak>=targetRom;const validTempo=duration>=rule.minRepMs&&duration<=rule.maxRepMs;if(!validRom){this.phase='up';return{counted:false,count:this.count,rom,confidence:conf,phase:'up',signal:rule.signal,error:'incomplete_rom'};}if(!validTempo){this.phase='up';return{counted:false,count:this.count,rom,confidence:conf,phase:'up',signal:rule.signal,error:'rushing_tempo'};}if(this.lastRepTs&&now-this.lastRepTs<rule.minRepMs){this.phase='up';return{counted:false,count:this.count,rom,confidence:conf,phase:'up',signal:rule.signal,error:'rushing_tempo'};}this.count++;this.lastRepTs=now;this.phase='up';const completed=this.peak;this.peak=0;return{counted:true,count:this.count,rom:completed,confidence:conf,phase:'up',signal:rule.signal};}}
 return{counted:false,count:this.count,rom,confidence:conf,phase:this.phase,signal:rule.signal};}
 private plank(p:LandmarkPoint[],now:number,conf:number):RepResult{const s=p[11]||p[12],h=p[23]||p[24],a=p[27]||p[28];if(!s||!h||!a)return{counted:false,count:0,rom:0,confidence:conf,phase:'paused',signal:'plank',error:'low_confidence'};const form=Math.max(0,100-Math.abs(180-calculateJointAngle3D(s,h,a))*2.2);if(form>=65){if(this.phase!=='hold')this.startTs=now;this.phase='hold';return{counted:false,count:Math.floor((now-this.startTs)/1000),rom:form,confidence:conf,phase:'hold',signal:'plank'};}this.phase='up';return{counted:false,count:0,rom:form,confidence:conf,phase:'up',signal:'plank',error:'poor_form'};}
}
