import React,{useEffect,useState} from 'react';
import { Mic,MicOff,PhoneCall,PhoneOff,Volume2,AlertCircle } from 'lucide-react';
import { authStore } from '../../services/authStore';
import { mediaSettingsStore } from '../../services/mediaSettingsStore';
import { voiceService } from '../../services/voiceService';
import { Avatar } from '../../ui/Avatar';
import { useI18n } from '../../services/i18n';
export interface BattleVoiceOverlayProps{matchId:string;opponentNick:string;opponentAvatar:string}
export const BattleVoiceOverlay:React.FC<BattleVoiceOverlayProps>=({matchId,opponentNick,opponentAvatar})=>{
 const {t}=useI18n(); const user=authStore.getUser(); const [connected,setConnected]=useState(false); const [muted,setMuted]=useState(false); const [speaking,setSpeaking]=useState(false); const [error,setError]=useState<string|null>(null); const [settings,setSettings]=useState(mediaSettingsStore.getSettings());
 useEffect(()=>{const u=mediaSettingsStore.subscribe(()=>setSettings(mediaSettingsStore.getSettings()));const v=voiceService.subscribe(()=>{setConnected(voiceService.getActiveRoomId()===`match_${matchId}`);setMuted(voiceService.getIsMuted());setSpeaking(voiceService.getIsSpeaking());setError(voiceService.micPermissionError)});return()=>{u();v();voiceService.leaveRoom()}},[matchId]);
 const join=async()=>{setError(null);const ok=await voiceService.joinRoom(`match_${matchId}`);if(!ok)setError(voiceService.micPermissionError||t.common.error)};
 return <div className="flex flex-col gap-2 p-3 rounded-2xl bg-[var(--bg-card)] border border-[var(--border-subtle)] shadow-lg"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-bold"><Volume2 size={15} className="text-[var(--accent)]"/><span>{t.battle.voiceTitle}</span></div>{!connected?<button onClick={join} className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[var(--accent)] text-white text-xs font-bold"><PhoneCall size={13}/>{t.chat.joinRoom}</button>:<div className="flex gap-1.5"><button onClick={()=>voiceService.toggleMute()} className="p-1.5 rounded-lg border">{muted?<MicOff size={14}/>:<Mic size={14}/>}</button><button onClick={()=>voiceService.leaveRoom()} className="p-1.5 rounded-lg bg-rose-500/20 border border-rose-500/40"><PhoneOff size={14}/></button></div>}</div>{error&&<div className="text-[11px] text-rose-400 flex items-center gap-1"><AlertCircle size={13}/>{error}</div>}{connected&&<div className="grid grid-cols-2 gap-2"><div className={`p-2 rounded-xl border ${speaking?'border-emerald-400':'border-[var(--border-subtle)]'}`}><div className="flex items-center gap-2"><Avatar avatar={user.avatar} size="sm"/><span>{user.nick}</span></div><div className="text-[9px] text-slate-400">{muted?t.chat.micOff:speaking?t.chat.speaking:t.chat.online}</div></div><div className="p-2 rounded-xl border border-[var(--border-subtle)]"><div className="flex items-center gap-2"><Avatar avatar={opponentAvatar} size="sm"/><span>{opponentNick}</span></div><div className="text-[9px] text-slate-400">{t.chat.online}</div></div></div>}</div>;
};
