import React,{useState} from 'react';
import {Heart,ExternalLink,Loader2,CheckCircle2,AlertCircle} from 'lucide-react';
import {Card} from '../../ui/Card';
import {Button} from '../../ui/Button';
import {useI18n} from '../../services/i18n';

type Currency='USDC'|'SOL';
export const SolanaDonation:React.FC=()=>{
 const {lang}=useI18n();
 const copy=lang==='en'?{title:'Support ForgeMuscle',desc:'Voluntary donation via Solana. The site never stores your seed phrase or private key.',amount:'Amount',donate:'Donate',open:'Open Solana Pay',signature:'Paste the transaction signature after payment',verify:'Verify donation',thanks:'Thank you for supporting ForgeMuscle! Donation confirmed.',invalid:'Enter a valid donation amount.',createError:'Could not create the donation.',verifyError:'The transaction is not confirmed yet.'}:lang==='uk'?{title:'Підтримати ForgeMuscle',desc:'Добровільний донат через Solana. Сайт не зберігає seed phrase або приватний ключ.',amount:'Сума',donate:'Задонатити',open:'Відкрити Solana Pay',signature:'Вставте signature після оплати',verify:'Перевірити донат',thanks:'Дякуємо за підтримку ForgeMuscle! Донат підтверджено.',invalid:'Вкажіть коректну суму донату.',createError:'Не вдалося створити донат.',verifyError:'Транзакція ще не підтверджена.'}:{title:'Support ForgeMuscle',desc:'Voluntary donation via Solana. The site never stores your seed phrase or private key.',amount:'Amount',donate:'Donate',open:'Open Solana Pay',signature:'Paste the transaction signature after payment',verify:'Verify donation',thanks:'Thank you for supporting ForgeMuscle! Donation confirmed.',invalid:'Enter a valid donation amount.',createError:'Could not create the donation.',verifyError:'The transaction is not confirmed yet.'};
 const [currency,setCurrency]=useState<Currency>('USDC');
 const [amount,setAmount]=useState('5');
 const [order,setOrder]=useState<any>(null);
 const [signature,setSignature]=useState('');
 const [status,setStatus]=useState<'idle'|'loading'|'pending'|'paid'|'error'>('idle');
 const [error,setError]=useState('');
 const presets=currency==='USDC'?['1','5','10','25']:['0.01','0.05','0.1','0.25'];
 const create=async()=>{setStatus('loading');setError('');try{const n=Number(amount);if(!Number.isFinite(n)||n<=0||n>10000)throw new Error(copy.invalid);const r=await fetch('/api/payments/donations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currency,amount:n})});const d=await r.json();if(!r.ok)throw new Error(d.error||copy.createError);setOrder(d.order);setStatus('pending');window.location.href=d.order.paymentUrl;}catch(e){setStatus('error');setError(e instanceof Error?e.message:copy.createError);}};
 const verify=async()=>{if(!order)return;setStatus('loading');setError('');try{const r=await fetch(`/api/payments/orders/${order.id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({signature})});const d=await r.json();if(!r.ok)throw new Error(d.error||copy.verifyError);setStatus('paid');setOrder(d.order);}catch(e){setStatus('error');setError(e instanceof Error?e.message:copy.verifyError);}};
 return <Card padding="md"><div className="flex items-center gap-2 font-heading font-bold"><Heart size={16} className="text-[var(--accent)]"/><span>{copy.title}</span></div><p className="text-xs text-[var(--text-secondary)] mt-1">{copy.desc}</p><div className="flex gap-2 mt-3">{(['USDC','SOL'] as Currency[]).map(c=><Button key={c} size="sm" variant={currency===c?'primary':'outline'} onClick={()=>{setCurrency(c);setAmount(c==='USDC'?'5':'0.05');setStatus('idle');setOrder(null);setSignature('');}}>{c}</Button>)}</div><div className="grid grid-cols-4 gap-2 mt-3">{presets.map(v=><button key={v} type="button" onClick={()=>setAmount(v)} className={`rounded-lg border px-2 py-2 text-xs font-semibold ${amount===v?'border-[var(--accent)] bg-[var(--accent)]/10':'border-[var(--border-subtle)] bg-[var(--bg-subtle)]'}`}>{v} {currency}</button>)}</div><div className="flex gap-2 mt-3"><input inputMode="decimal" className="min-w-0 flex-1 rounded-lg bg-[var(--bg-subtle)] border border-[var(--border-subtle)] px-3 py-2 text-sm" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={copy.amount}/><Button onClick={create} disabled={status==='loading'}>{status==='loading'?<Loader2 className="animate-spin" size={14}/>:copy.donate}</Button></div>{order&&status!=='paid'&&<div className="mt-3 space-y-2"><a className="text-xs underline inline-flex items-center gap-1" href={order.paymentUrl}>{copy.open} <ExternalLink size={12}/></a><input className="w-full rounded-lg bg-[var(--bg-subtle)] border border-[var(--border-subtle)] px-3 py-2 text-xs" placeholder={copy.signature} value={signature} onChange={e=>setSignature(e.target.value)}/><Button className="w-full" onClick={verify} disabled={!signature||status==='loading'}>{status==='loading'?<Loader2 className="animate-spin" size={14}/>:copy.verify}</Button></div>}{status==='paid'&&<div className="mt-3 text-sm text-emerald-400 flex items-center gap-2"><CheckCircle2 size={16}/>{copy.thanks}</div>}{status==='error'&&<div className="mt-3 text-xs text-rose-400 flex items-center gap-2"><AlertCircle size={14}/>{error}</div>}</Card>;
};
