import React,{useState} from 'react';
import {Heart,ExternalLink,Loader2,CheckCircle2,AlertCircle} from 'lucide-react';
import {Card} from '../../ui/Card';
import {Button} from '../../ui/Button';
import {useI18n} from '../../services/i18n';

type Currency='USDC'|'SOL';
export const SolanaPlayerDonation:React.FC<{battleId:string;targetUserId:string;targetNick:string}> = ({battleId,targetUserId,targetNick})=>{
 const {lang}=useI18n();
 const copy=lang==='en'?{title:`Tip ${targetNick}`,desc:'Voluntary tip to this player. It is not a wager and does not affect the battle result.',amount:'Amount',donate:'Tip player',open:'Open wallet',signature:'Paste transaction signature',verify:'Verify tip',thanks:'Tip confirmed!',invalid:'Enter a valid amount.',createError:'Could not create the tip.',verifyError:'Transaction is not confirmed yet.'}:{title:`Донат ${targetNick}`,desc:'Добровільний донат цьому гравцю. Це не ставка і не впливає на результат бою.',amount:'Сума',donate:'Задонатити',open:'Відкрити гаманець',signature:'Вставте signature транзакції',verify:'Перевірити',thanks:'Донат підтверджено!',invalid:'Вкажіть коректну суму.',createError:'Не вдалося створити донат.',verifyError:'Транзакція ще не підтверджена.'};
 const [currency,setCurrency]=useState<Currency>('USDC'); const [amount,setAmount]=useState('1'); const [order,setOrder]=useState<any>(null); const [signature,setSignature]=useState(''); const [status,setStatus]=useState<'idle'|'loading'|'pending'|'paid'|'error'>('idle'); const [error,setError]=useState('');
 const presets=currency==='USDC'?['1','5','10','25']:['0.01','0.05','0.1','0.25'];
 const create=async()=>{setStatus('loading');setError('');try{const n=Number(amount);if(!Number.isFinite(n)||n<=0||n>10000)throw new Error(copy.invalid);const r=await fetch('/api/payments/player-donations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({battleId,targetUserId,currency,amount:n})});const d=await r.json();if(!r.ok)throw new Error(d.error||copy.createError);setOrder(d.order);setStatus('pending');window.location.href=d.order.paymentUrl;}catch(e){setStatus('error');setError(e instanceof Error?e.message:copy.createError);}};
 const verify=async()=>{if(!order)return;setStatus('loading');setError('');try{const r=await fetch(`/api/payments/orders/${order.id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({signature})});const d=await r.json();if(!r.ok)throw new Error(d.error||copy.verifyError);setStatus('paid');setOrder(d.order);}catch(e){setStatus('error');setError(e instanceof Error?e.message:copy.verifyError);}};
 return <Card padding="md"><div className="flex items-center gap-2 font-heading font-bold"><Heart size={16} className="text-[var(--accent)]"/><span>{copy.title}</span></div><p className="text-xs text-[var(--text-secondary)] mt-1">{copy.desc}</p><div className="flex gap-2 mt-3">{(['USDC','SOL'] as Currency[]).map(c=><Button key={c} size="sm" variant={currency===c?'primary':'outline'} onClick={()=>{setCurrency(c);setAmount(c==='USDC'?'1':'0.01');setStatus('idle');setOrder(null);setSignature('');}}>{c}</Button>)}</div><div className="grid grid-cols-4 gap-2 mt-3">{presets.map(v=><button key={v} type="button" onClick={()=>setAmount(v)} className={`rounded-lg border px-2 py-2 text-xs font-semibold ${amount===v?'border-[var(--accent)] bg-[var(--accent)]/10':'border-[var(--border-subtle)] bg-[var(--bg-subtle)]'}`}>{v}</button>)}</div><div className="flex gap-2 mt-3"><input inputMode="decimal" className="min-w-0 flex-1 rounded-lg bg-[var(--bg-subtle)] border border-[var(--border-subtle)] px-3 py-2 text-sm" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={copy.amount}/><Button onClick={create} disabled={status==='loading'}>{status==='loading'?<Loader2 className="animate-spin" size={14}/>:copy.donate}</Button></div>{order&&status!=='paid'&&<div className="mt-3 space-y-2"><a className="text-xs underline inline-flex items-center gap-1" href={order.paymentUrl}>{copy.open} <ExternalLink size={12}/></a><input className="w-full rounded-lg bg-[var(--bg-subtle)] border border-[var(--border-subtle)] px-3 py-2 text-xs" placeholder={copy.signature} value={signature} onChange={e=>setSignature(e.target.value)}/><Button className="w-full" onClick={verify} disabled={!signature||status==='loading'}>{status==='loading'?<Loader2 className="animate-spin" size={14}/>:copy.verify}</Button></div>}{status==='paid'&&<div className="mt-3 text-sm text-emerald-400 flex items-center gap-2"><CheckCircle2 size={16}/>{copy.thanks}</div>}{status==='error'&&<div className="mt-3 text-xs text-rose-400 flex items-center gap-2"><AlertCircle size={14}/>{error}</div>}</Card>;
};
