import React,{useEffect,useState} from 'react';
import {CreditCard,ExternalLink,Loader2,CheckCircle2,AlertCircle,Wallet} from 'lucide-react';
import {Connection,PublicKey,SystemProgram,Transaction,LAMPORTS_PER_SOL,TransactionInstruction} from '@solana/web3.js';
import {Card} from '../../ui/Card'; import {Button} from '../../ui/Button';
import {connectSolanaWallet,getSolanaProvider,shortAddress} from '../../services/solanaWallet';

const RPC_BY_CLUSTER:{[key:string]:string}={devnet:'https://api.devnet.solana.com','mainnet-beta':'https://api.mainnet-beta.solana.com',testnet:'https://api.testnet.solana.com'};
const TOKEN_PROGRAM_ID=new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');
const ASSOCIATED_TOKEN_PROGRAM_ID=new PublicKey('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL');
const SYSTEM_PROGRAM_ID=SystemProgram.programId;
function ata(owner:PublicKey,mint:PublicKey){return PublicKey.findProgramAddressSync([owner.toBuffer(),TOKEN_PROGRAM_ID.toBuffer(),mint.toBuffer()],ASSOCIATED_TOKEN_PROGRAM_ID)[0];}
function createAtaInstruction(payer:PublicKey,owner:PublicKey,mint:PublicKey,address:PublicKey){return new TransactionInstruction({programId:ASSOCIATED_TOKEN_PROGRAM_ID,keys:[{pubkey:payer,isSigner:true,isWritable:true},{pubkey:address,isSigner:false,isWritable:true},{pubkey:owner,isSigner:false,isWritable:false},{pubkey:mint,isSigner:false,isWritable:false},{pubkey:SYSTEM_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:TOKEN_PROGRAM_ID,isSigner:false,isWritable:false}],data:new Uint8Array(0)});}
function transferCheckedInstruction(source:PublicKey,mint:PublicKey,destination:PublicKey,owner:PublicKey,amount:bigint,decimals:number){const data=new Uint8Array(10);data[0]=12;const view=new DataView(data.buffer);view.setBigUint64(1,amount,true);data[9]=decimals;return new TransactionInstruction({programId:TOKEN_PROGRAM_ID,keys:[{pubkey:source,isSigner:false,isWritable:true},{pubkey:mint,isSigner:false,isWritable:false},{pubkey:destination,isSigner:false,isWritable:true},{pubkey:owner,isSigner:true,isWritable:false}],data});}

export const SolanaCheckout:React.FC=()=>{
 const [currency,setCurrency]=useState<'USDC'|'SOL'>('USDC'); const [product,setProduct]=useState<any>(null); const [order,setOrder]=useState<any>(null); const [signature,setSignature]=useState(''); const [status,setStatus]=useState<'idle'|'loading'|'pending'|'paid'|'error'>('idle'); const [error,setError]=useState(''); const [wallet,setWallet]=useState('');
 useEffect(()=>{fetch('/api/payments/products').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Не вдалося завантажити продукт.');setProduct(d.products?.[0]);}).catch(e=>setError(e instanceof Error?e.message:'Не вдалося завантажити продукт.'));},[]);
 const connectWallet=async()=>{const provider=getSolanaProvider();if(!provider)throw new Error('Встановіть Phantom або Solflare.');const address=provider.publicKey?.toString();if(!address) { const r=await provider.connect(); return {provider,publicKey:new PublicKey(r.publicKey.toString())}; } return {provider,publicKey:new PublicKey(address)};};
 const create=async()=>{setStatus('loading');setError('');try{await connectSolanaWallet();const connected=await connectWallet();setWallet(connected.publicKey.toString());const r=await fetch('/api/payments/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:product.id,currency})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Не вдалося створити замовлення.');setOrder(d.order);setStatus('pending');await pay(d.order);}catch(e){setStatus('error');setError(e instanceof Error?e.message:'Не вдалося створити оплату.');}};
 const pay=async(o:any)=>{const provider=getSolanaProvider();if(!provider)throw new Error('Гаманець не підключено.');const address=provider.publicKey?.toString();if(!address)throw new Error('Гаманець не підключено.');const payer=new PublicKey(address);setWallet(address);const cluster=o.network||'devnet';const connection=new Connection(RPC_BY_CLUSTER[cluster]||RPC_BY_CLUSTER.devnet,'confirmed');const recipient=new PublicKey(o.recipient);const reference=new PublicKey(o.reference);const tx=new Transaction();
  if(o.currency==='SOL'){const ix=SystemProgram.transfer({fromPubkey:payer,toPubkey:recipient,lamports:Math.round(Number(o.amount)*LAMPORTS_PER_SOL)});ix.keys.push({pubkey:reference,isSigner:false,isWritable:false});tx.add(ix);}
  else {const mint=new PublicKey(o.tokenMint);const source=ata(payer,mint);const destination=ata(recipient,mint);const info=await connection.getAccountInfo(destination);if(!info)tx.add(createAtaInstruction(payer,recipient,mint,destination));const ix=transferCheckedInstruction(source,mint,destination,payer,BigInt(Math.round(Number(o.amount)*1_000_000)),6);ix.keys.push({pubkey:reference,isSigner:false,isWritable:false});tx.add(ix);}
  tx.feePayer=payer;tx.recentBlockhash=(await connection.getLatestBlockhash('confirmed')).blockhash;if(!provider.sendTransaction)throw new Error('Цей гаманець не підтримує надсилання транзакцій у браузері. Відкрийте Solana Pay у Phantom або Solflare.');const result=await provider.sendTransaction(tx,connection);setSignature(result);await verify(result,o.id);
 };
 const verify=async(sig:string,id:string)=>{setStatus('loading');setError('');try{const r=await fetch(`/api/payments/orders/${id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({signature:sig})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Транзакція ще не підтверджена.');setStatus('paid');setOrder(d.order||order);}catch(e){setStatus('error');setError(e instanceof Error?e.message:'Платіж ще не підтверджено.');}};
 if(!product)return <Card padding="md"><div className="text-sm">Checkout завантажується…</div>{error&&<p className="text-xs text-rose-400 mt-2">{error}</p>}</Card>;
 return <Card padding="md"><div className="flex items-center gap-2 font-heading font-bold"><CreditCard size={16}/><span>ForgeMuscle Premium</span></div><p className="text-xs text-[var(--text-secondary)] mt-1">Підключіть гаманець і підтвердьте оплату у Phantom або Solflare.</p>{wallet&&<div className="mt-2 text-xs text-[var(--text-secondary)] flex items-center gap-1"><Wallet size={13}/> {shortAddress(wallet)}</div>}<div className="flex gap-2 mt-3">{(['USDC','SOL'] as const).map(c=><Button key={c} size="sm" variant={currency===c?'primary':'outline'} onClick={()=>setCurrency(c)} disabled={status==='loading'}>{c} · {c==='USDC'?product.prices.USDC:product.prices.SOL}</Button>)}</div>{status==='idle'&&<Button className="mt-3 w-full" onClick={create}><Wallet size={15}/> Підключити гаманець і оплатити</Button>}{order&&status!=='paid'&&<div className="mt-3 space-y-2"><div className="text-xs text-[var(--text-secondary)] break-all">Order: {order.id}<br/>Reference: {order.reference}</div><a className="text-xs underline inline-flex items-center gap-1" href={order.paymentUrl} target="_blank" rel="noreferrer">Відкрити Solana Pay <ExternalLink size={12}/></a>{signature&&<div className="text-xs text-[var(--text-secondary)] break-all">Transaction: {signature}</div>}{status==='pending'&&<div className="text-xs text-[var(--text-secondary)]">Очікуємо підтвердження транзакції…</div>}<input className="w-full rounded-lg bg-[var(--bg-subtle)] border border-[var(--border-subtle)] px-3 py-2 text-xs" placeholder="Signature для повторної перевірки" value={signature} onChange={e=>setSignature(e.target.value)}/><Button className="w-full" onClick={()=>verify(signature,order.id)} disabled={!signature||status==='loading'}>{status==='loading'?<Loader2 className="animate-spin" size={14}/>: 'Перевірити оплату сервером'}</Button></div>}{status==='paid'&&<div className="mt-3 text-sm text-emerald-400 flex items-center gap-2"><CheckCircle2 size={16}/> Оплату підтверджено. Premium активовано.</div>}{status==='error'&&<div className="mt-3 text-xs text-rose-400 flex items-center gap-2"><AlertCircle size={14}/>{error}</div>}</Card>;
};
